spring:
  application:
    name: Tas
  profiles:
    active: dev
    group:
      dev:
        - auth
        - databases
        - wallet
        - logging
        - spring-docs
        - setup
        - blockchain
      sample:
        - auth
        - databases-sample
        - wallet
        - logging
        - spring-docs
        - setup
      lss:
        - lss
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "shutdown"
  endpoint:
    health:
      show-details: "never"
    shutdown:
      enabled: true

server:
  port: 8090
